[package]
name = "elodin"
version = "1.0.1"
authors = ["Ben Christianson <thhuntertgm@gmail.com>"]

[dependencies]
clap = { version = "4.3.10", features = ["cargo"] }
Inflector = "0.11.4"
rand = "0.8.5"
