[package]
name = "elodin"
version = "1.0.3"
edition = "2024"
authors = ["Ben Christianson <thhuntertgm@gmail.com>"]

[dependencies]
clap = { version = "4.5.47", features = ["cargo"] }
inflector-plus = "0.11.7"
rand = "0.9.2"
